services:
  supervisorapi:
    build:
      context: .
    image: mrbolas/supervisorapi:latest
    ports:
      - "8080:8080" # http
    env_file:
      - .env
    depends_on:
      - db
    restart: on-failure

  db:
    image: mysql:5.7
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sh_supervisor
    volumes:
      - db-data:/var/lib/mysql
    restart: unless-stopped

volumes:
 db-data: