apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yaml convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: queue
  name: queue
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: queue
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.yaml convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: queue
    spec:
      containers:
        - image: redis
          name: queue
          ports:
            - containerPort: 6379
          resources: {}
      restartPolicy: Always
status: {}
